/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'gustavo' at '9/27/16 4:22 PM' with Gradle 2.12
 *
 * @author gustavo, @date 9/27/16 4:22 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
